In [2]:
#
#    IMPORTS
#

#    These are standard python modules. In case you do not have a python module, you should use `!pip install <module>`
import pandas as pd
#

In [3]:
# Read the Excel file and skip the first 3 rows
df = pd.read_excel('../Raw Data/By Procedures/proc300.xls', header=1)
print(df)

   Number of Procedures by Category and County of Residence, Arizona, 2000  \
0                                                  \n
1
2                                                 NaN
3                    Operations on the nervous system
4                                          Spinal tap
5                               Operations on the eye
6                               Operations on the ear
7            Operations on the nose mouth and pharynx
8                Operations on the respiratory system
9                 Bronchoscopy with or without biopsy
10            Operations on the cardiovascular system
11             Removal of coronary artery obstruction
12                       Coronary artery bypass graft
13                            Cardiac catheterization
14          Insertion, replacement, removal, and r...
15                                       Hemodialysis
16       Operations on the hemic and lymphatic system
17                 Operations on the digestive system
18          Endoscopy of small intestine with or w...
19          Endoscopy of large intestine with or w...
20                Partial excision of large intestine
21                 Appendectomy, excluding incidental
22                                    Cholecystectomy
23                      Lysis of peritoneal adhesions
24                   Operations on the urinary system
25                  Cystoscopy with or without biopsy
26              Operations on the male genital organs
27                                      Prostatectomy
28            Operations on the female genital organs
29             Oophorectomy and salpingo-oophorectomy
30          Bilateral destruction or occlusion of ...
31                             Obstetrical procedures
32          Episiotomy with or without forceps or ...
33                    Artificial rupture of membranes
34             Repair of current obstetric laceration
35           Operations on the musculoskeletal system
36                           Partial excision of bone
37                              Reduction of fracture
38          Open reduction of fracture with intern...
39          Excision or destruction of interverteb...
40                              Total hip replacement
41                             Total knee replacement
42             Operations on the integumentary system
43           Debridement of wound, infection, or burn
44  Miscellaneous diagnostic and therapeutic proce...
45                      Computerized axial tomography
46          Arteriography and angiocardiography us...
47                              Diagnostic ultrasound
48                                Respiratory therapy
49                     Insertion of endotracheal tube
50          Injection or infusion of cancer chemot...

   Unnamed: 1           Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN                  NaN        NaN        NaN        NaN
1       Total  County of Residence        NaN        NaN        NaN
2         NaN               Apache    Cochise   Coconino       Gila
3       22758                  136        370        354        353
4        4739                   24         54         65         44
5        2995                   15         99         47        123
6         377                    3          7         14         27
7        2603                   23         54         62         45
8       12651                   71        184        174        169
9        4221                   22         70         51         45
10      66693                  293       1295        880       1035
11      11854                   56        357        150        229
12       5953                   26        136         66         99
13      24736                  121        656        288        381
14       3598                   11         73         40         50
15       8534                   32        112        144        132
16       4795                   23        114         66         61
17      58997                  264        994        926       1099
18      13275                   65        216        130        305
19       7685                   37         80         72        203
20       3642                   13         42         51         51
21       6145                   23         80        126         62
22       9707                   43        201        193        193
23       5825                   21        118         89        122
24       9030                   53        173        122        137
25       2828                   16         36         43         30
26       3415                   20         61         45         31
27       2761                   13         48         33         22
28      20596                   87        394        362        333
29       8423                   37        146        167        119
30       4058                   24         84         66         84
31      63336                  195        813       1057        516
32      10469                   17         94        156         66
33      19809                   71        353         65        249
34      22437                   34        278        401        134
35      38898                  242        690        809        596
36       3798                   44         88        133         57
37       9003                   75        149        237        126
38       6510                   42        104        159         75
39       4277                   28         83        152         43
40       2715                   11         32         41         31
41       5205                   22        118         64         86
42      15852                   68        253        238        513
43       4016                   22         67         63         96
44      88980                  530       1678       1121       1625
45       1039                   10         17         35          6
46      30390                  140        832        363        498
47       2989                   59         32         98         28
48      11886                   87        236        185        186
49       8895                   44        149        108         95
50       2897                   14         65         22         42

   Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0         NaN        NaN        NaN        NaN         NaN         NaN
1         NaN        NaN        NaN        NaN         NaN         NaN
2      Graham   Greenlee     La Paz   Maricopa      Mohave      Navajo
3          74         27         55      14625         557         468
4          11          9          9       3165         117          54
5          13          6         13       1305          51          28
6           0          1          1        196           9           9
7          13          3         13       1552          88          47
8          37         11         58       7964         426         170
9          12          5         14       2641         132          72
10        247         82        317      39803        2918        1004
11         50         24         61       6641         571         140
12         29         11         27       3637         153          86
13        104         56        126      14487        1007         349
14         24          9         12       1886         157          47
15         28          3         87       4985         269         218
16         19          3         17       2902          99          57
17        135         37        282      35436        2084         990
18         25          7        102       7776         503         162
19         12          4         43       4672         319          95
20          3          2         15       2302         169          29
21          8          3         16       4143         155         129
22         12          3         43       5397         370         202
23         30          5         22       3468         205          44
24         47         11         56       5337         374         230
25          5          2         17       1750         182          92
26          3          0         24       2101         180          67
27          2          0         22       1704         144          58
28        378         74         60      11843         627         369
29         50          6         30       5005         260         159
30          4          1          6       2175         173          93
31        247         59         73      43009         989         816
32         23          6          1       8009         273          89
33         38          5         42      13046         356         405
34          7          2         12      16209         199         215
35       1219        239        114      21218        1073         692
36         19          6          6       1980          87          74
37         61         18         30       5293         268         196
38         25          7         22       3945         211         131
39         17          8          8       2360          58          92
40         10          3         10       1681         102          36
41         20          6         13       3012         187          69
42       1058        206         52       8436         425         274
43          8          1         15       2289         110          89
44        886        229        363      50515        3359        1779
45          0          1          6        270          50          17
46        135         59        106      17248        1319         424
47          8          3         16       1583         113         258
48         39         12         66       6788         451         245
49         17          9         38       5243         342         162
50          1          9          1       1784          15          30

   Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2         Pima       Pinal  Santa Cruz     Yavapai        Yuma     Unknown
3         3262         862         122         933         558           2
4          678         201          27         121         160           0
5         1040          73          28          97          57           0
6           62          14           6          15          13           0
7          456          89          20          77          60           1
8         1820         569          61         512         419           6
9          617         162          21         162         191           4
10       10005        3636         363        2686        2112          17
11        1847         683          57         640         344           4
12         891         328          29         294         139           2
13        3980        1246         138         971         818           8
14         774         181          33         192         109           0
15        1294         717          61         200         251           1
16         882         202          38         211          99           2
17        9218        2716         473        2357        1969          17
18        2210         607          63         476         623           5
19        1134         318          41         309         346           0
20         522         141          15         168         119           0
21         681         311          48         204         154           2
22        1591         513         115         514         312           5
23        1007         270          43         296          84           1
24        1425         317          59         327         359           3
25         310          53          18         112         161           1
26         493         118          21         152          97           2
27         391          81          19         133          89           2
28        3569         879         200         838         580           3
29        1341         340          65         469         229           0
30         866         176          40          98         165           3
31        8963        2037         775        1220        2544          23
32         783         330          44         268         304           6
33        3533         474         411         301         455           5
34        2426         635         228         419        1229           9
35        7425        1549         225        1766        1033           8
36         834         140          12         226          91           1
37        1548         324          71         362         242           3
38        1052         241          52         267         175           2
39         927         164          24         237          76           0
40         423         113           8         145          69           0
41         883         274          27         282         142           0
42        2596         653         129         518         428           5
43         702         246          35         139         129           5
44       15370        4084         518        4259        2638          26
45         407           9           7         160          44           0
46        5259        1534         183        1209        1069          12
47         434          96          12         149          99           1
48        2120         569          97         378         422           5
49        1759         440          65         257         165           2
50         576         155          25          75          83           0

In [4]:
# Read the Excel file and skip the first 3 rows
df = pd.read_excel('../Raw Data/By Procedures/proc300.xls', skiprows=3, header=1)
df.rename(columns={'Unnamed: 0': 'Procedure', 'Unnamed: 1': 'Total'}, inplace=True)
df['Procedure'] = df['Procedure'].str.strip()  # Clean up spaces before and after

print(df['Procedure'].unique())

# Filter the dataframe for the specified procedures and column
procedures = ['Respiratory therapy', 'Operations on the respiratory system']
filtered_df = df[df['Procedure'].isin(procedures)][['Procedure', 'Maricopa']]

print(filtered_df)

['Operations on the nervous system' 'Spinal tap' 'Operations on the eye'
 'Operations on the ear' 'Operations on the nose mouth and pharynx'
 'Operations on the respiratory system'
 'Bronchoscopy with or without biopsy'
 'Operations on the cardiovascular system'
 'Removal of coronary artery obstruction' 'Coronary artery bypass graft'
 'Cardiac catheterization'
 'Insertion, replacement, removal, and revision of pacemaker leads or device'
 'Hemodialysis' 'Operations on the hemic and lymphatic system'
 'Operations on the digestive system'
 'Endoscopy of small intestine with or without biopsy'
 'Endoscopy of large intestine with or without biopsy'
 'Partial excision of large intestine'
 'Appendectomy, excluding incidental' 'Cholecystectomy'
 'Lysis of peritoneal adhesions' 'Operations on the urinary system'
 'Cystoscopy with or without biopsy'
 'Operations on the male genital organs' 'Prostatectomy'
 'Operations on the female genital organs'
 'Oophorectomy and salpingo-oophorectomy'
 'Bilateral destruction or occlusion of fallopian tubes'
 'Obstetrical procedures'
 'Episiotomy with or without forceps or vacuum extraction'
 'Artificial rupture of membranes'
 'Repair of current obstetric laceration'
 'Operations on the musculoskeletal system' 'Partial excision of bone'
 'Reduction of fracture'
 'Open reduction of fracture with internal fixation'
 'Excision or destruction of intervertebral disc' 'Total hip replacement'
 'Total knee replacement' 'Operations on the integumentary system'
 'Debridement of wound, infection, or burn'
 'Miscellaneous diagnostic and therapeutic procedures'
 'Computerized axial tomography'
 'Arteriography and angiocardiography using contrast material'
 'Diagnostic ultrasound' 'Respiratory therapy'
 'Insertion of endotracheal tube'
 'Injection or infusion of cancer chemotherapeutic substance']
                               Procedure  Maricopa
5   Operations on the respiratory system      7964
45                   Respiratory therapy      6788

In [ ]:
import pandas as pd
import glob

# Define the folder path and file pattern
folder_path = '../Raw Data/By Procedures/'
file_pattern = folder_path + '*.xls*'

# Define the procedures of interest
procedures = ['Respiratory therapy', 'Operations on the respiratory system']


# Initialize dictionaries to store dataframes for each procedure
procedure_dfs = {procedure: [] for procedure in procedures}

for file_path in glob.glob(file_pattern):
    # Extract the year from the file name
    file_name = file_path.split('/')[-1]
    year = file_name.split('.')[0][-2:] 
    year = '20' + year  # Convert to full year
    
    if year in ['2000', '2001', '2002', '2003']:
        # Read the file and skip the first 3 rows
        df = pd.read_excel(file_path, skiprows=3, header=1)
        # Rename columns and clean up
        df.rename(columns={'Unnamed: 0': 'Procedure', 'Unnamed: 1': 'Total State'}, inplace=True)
    else:
        df = pd.read_excel(file_path, skiprows=2, header=1)
        # Rename columns and clean up
        df.rename(columns={'Procedures by category': 'Procedure'}, inplace=True)
    
    # Print column names for debugging
    print(f"Columns in {file_name}: {df.columns.tolist()}")
    
    df['Procedure'] = df['Procedure'].str.strip()  # Clean up spaces
    
    # Filter the dataframe for the specified procedures and Maricopa column
    for procedure in procedures:
        filtered_df = df[df['Procedure'] == procedure][['Procedure', 'Maricopa']].copy()
        if not filtered_df.empty:
            # Rename columns and add year column
            filtered_df.rename(columns={'Maricopa': 'Total'}, inplace=True)
            filtered_df['Year'] = year
            # Append to the corresponding list
            procedure_dfs[procedure].append(filtered_df)

# Combine all dataframes for each procedure into a single dataframe
final_dfs = {procedure: pd.concat(dfs, ignore_index=True) for procedure, dfs in procedure_dfs.items()}

# Reorder columns for clarity
for procedure in final_dfs:
    final_dfs[procedure] = final_dfs[procedure][['Year', 'Total']]

# Extract the final dataframes
final_df_respiratory_therapy = final_dfs['Respiratory therapy']
final_df_operations_respiratory_system = final_dfs['Operations on the respiratory system']

print(final_df_respiratory_therapy)
print(final_df_operations_respiratory_system)

Columns in By Procedures\proc300.xls: ['Procedure', 'Total State', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc301.xls: ['Procedure', 'Total State', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc302.xls: ['Procedure', 'Total State', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc304.xls: ['Procedure', ' Total State ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc305.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc306.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc307.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc308.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc309.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc310.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc311.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc312.xls: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc313.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc314.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc315.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc316.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc317.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc318.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc319.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
Columns in By Procedures\proc320.xlsx: ['Procedure', ' Total ', 'Apache', 'Cochise', 'Coconino', 'Gila', 'Graham', 'Greenlee', 'La Paz', 'Maricopa', 'Mohave', 'Navajo', 'Pima', 'Pinal', 'Santa Cruz', 'Yavapai', 'Yuma', 'Unknown']
    Year  Total
0   2000   6788
1   2001   7220
2   2002   7801
3   2004   9819
4   2005  11796
5   2006  12290
6   2007  12970
7   2008  14531
8   2009  16002
9   2010  16570
10  2011  16616
11  2012  16679
12  2013  16612
13  2014  16676
14  2015  16711
    Year  Total
0   2000   7964
1   2001   8953
2   2002   9507
3   2004  10951
4   2005  11804
5   2006  12709
6   2007  13075
7   2008  13985
8   2009  14571
9   2010  14161
10  2011  14129
11  2012  13849
12  2013  14030
13  2014  14002
14  2015  15096
15  2016  18683
16  2017  18764
17  2018  19743
18  2019  19954
19  2020  20724

In [33]:
final_df_respiratory_therapy

    Year  Total
0   2000   6788
1   2001   7220
2   2002   7801
3   2004   9819
4   2005  11796
5   2006  12290
6   2007  12970
7   2008  14531
8   2009  16002
9   2010  16570
10  2011  16616
11  2012  16679
12  2013  16612
13  2014  16676
14  2015  16711

In [34]:
final_df_operations_respiratory_system

    Year  Total
0   2000   7964
1   2001   8953
2   2002   9507
3   2004  10951
4   2005  11804
5   2006  12709
6   2007  13075
7   2008  13985
8   2009  14571
9   2010  14161
10  2011  14129
11  2012  13849
12  2013  14030
13  2014  14002
14  2015  15096
15  2016  18683
16  2017  18764
17  2018  19743
18  2019  19954
19  2020  20724

In [35]:
final_df_respiratory_therapy.to_csv('../Processed Data/2000_2015respiratory_therapy.csv', index=False)
final_df_operations_respiratory_system.to_csv('../Processed Data/2000_2020_respiratory_system_operations.csv', index=False)